<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="azstorageexp" ignored="0" name="test name SECOND" tests="5" failures="1" timestamp="16 Feb 2020 08:20:49 GMT" time="5.665" errors="0">
  <testcase name="oAuthTokenService" time="1.517" classname="serviceTests.AddToCartTest"/>
  <testcase name="signInUsingService" time="0.212" classname="serviceTests.AddToCartTest"/>
  <testcase name="searchSofaService" time="0.348" classname="serviceTests.AddToCartTest"/>
  <testcase name="getProductDetailsService" time="0.057" classname="serviceTests.AddToCartTest"/>
  <testcase name="addProductToCart" time="0.053" classname="serviceTests.AddToCartTest">
    <failure type="java.lang.AssertionError" message="expected [201] but found [409]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [409]
at services.cart.AddToCartRequest.verifyaddToCartResponseStatusCode(AddToCartRequest.java:35)
at serviceTests.AddToCartTest.addProductToCart(AddToCartTest.java:68)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addProductToCart -->
</testsuite> <!-- test name SECOND -->
